Algoritmo "IMC"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/11/2022
Var
// Seção de Declarações das variáveis 
Altura : inteiro
peso : real
IMC : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Altura <- 80
peso <- 3.24
IMC <- (Altura/peso)

escreva(IMC)

Fimalgoritmo