Algoritmo "media"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2022
Var
// Seção de Declarações das variáveis 
media: real
n1, n2, n3: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
n1 <- 8
n2 <- 9
n3 <- 5
media <- n1 + n2 + n3 / 3
escreva ("media", media)

Fimalgoritmo