Algoritmo "VALETRANSPORTE"
//Criamos um algoritmo que calcula o valor do vale transporte

Var
//Entrada: Salario,porcentagem,valor
//Processamento : Cauculo de vale transporte
//Saída : valor

  Salario : real
  porcentagem : real
  valor : real

Inicio

  escreval ("Salário:")
  leia(Salario)
  
  porcentagem <- 0.06
  valor <- Salario * porcentagem
  escreva(valor)

Fimalgoritmo